version: "3"

services:
  fastapi:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=localhost"
    ports:
      - 8000:8000

  react:
    image: frontend-react
    build: .
    working_dir: /frontend/IML_frontend
    volumes:
      - ./frontend/IML_frontend:/frontend/IML_frontend
    # command: sh -c "npm install && npm run dev -- --port 3000"
    ports:
      - 3000:3000
    depends_on:
      - fastapi
